2020-07-09 08:51:32.906 [error] <0.1730.0> CRASH REPORT Process <0.1730.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:51:32.906 [error] <0.1730.0> Cowboy stream 10 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1664.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:32.141 [error] <0.6282.0> CRASH REPORT Process <0.6282.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:32.142 [error] <0.6282.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6081.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :content, :current_user, :flash, :inner_content, :live_action, :live_module, :users, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:32.154 [error] <0.6288.0> CRASH REPORT Process <0.6288.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 18:33:32.155 [error] <0.6288.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.6287.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @socket not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :current_user, :inner_content, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:27:49.818 [error] <0.10407.0> CRASH REPORT Process <0.10407.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:27:49.829 [error] <0.10407.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.10406.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"1">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:38:13.278 [error] <0.11099.0> CRASH REPORT Process <0.11099.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"2">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:38:13.282 [error] <0.11099.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.11098.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => mount,kind => nil,module => 'Elixir.FidelityAppWeb.AdminuserLive.Show'},[{'Elixir.FidelityAppWeb.AdminuserLive.Show',mount,[#{<<"id">> => <<"2">>},#{<<"_csrf_token">> => <<"g3yhJiwH1Avmjm-lSnQnUKVx">>,<<"live_socket_id">> => <<"users_sessions:3QCDGpNkEHuPQbOqDdFaE1Iy80qXwN2mxG_uTJIPMsg=">>,<<"user_token">> => <<221,0,131,26,147,100,16,123,143,65,179,170,13,209,90,19,...>>},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:40:41.807 [error] <0.1155.0> CRASH REPORT Process <0.1155.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 19:40:41.809 [error] <0.1155.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1154.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @user not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-10 20:14:27.279 [error] <0.2558.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2557.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"giving a struct to Ecto.Repo.update/2 is not supported. Ecto is unable to properly track changes when a struct is given, an Ecto.Changeset must be given instead">>},[{'Elixir.Ecto.Repo.Schema',update,4,[{file,"lib/ecto/repo/schema.ex"},{line,292}]},{'Elixir.FidelityAppWeb.AdminuserLive.Edit',mount,3,[{file,"lib/fidelity_app_web/live/adminuser_live/edit.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-maybe_call_live_view_mount!/4-fun-0-',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
