2020-07-13 00:02:37.421 [error] <0.1818.0> CRASH REPORT Process <0.1818.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 00:02:37.422 [error] <0.1818.0> Cowboy stream 26 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1520.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 00:31:53.954 [info] <0.43.0> Application lager started on node nonode@nohost
2020-07-13 00:31:53.975 [info] <0.43.0> Application gen_stage started on node nonode@nohost
2020-07-13 00:31:53.980 [info] <0.43.0> Application broadway started on node nonode@nohost
2020-07-13 00:31:53.999 [info] <0.43.0> Application xmerl started on node nonode@nohost
2020-07-13 00:31:54.038 [info] <0.43.0> Application sasl started on node nonode@nohost
2020-07-13 00:31:54.050 [info] <0.43.0> Application tools started on node nonode@nohost
2020-07-13 00:31:54.059 [info] <0.43.0> Application jsx started on node nonode@nohost
2020-07-13 00:31:54.065 [info] <0.43.0> Application recon started on node nonode@nohost
2020-07-13 00:31:54.107 [info] <0.43.0> Application credentials_obfuscation started on node nonode@nohost
2020-07-13 00:31:54.107 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2020-07-13 00:31:54.124 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2020-07-13 00:31:54.128 [info] <0.43.0> Application amqp started on node nonode@nohost
2020-07-13 00:31:54.129 [info] <0.43.0> Application broadway_rabbitmq started on node nonode@nohost
2020-07-13 00:31:54.228 [info] <0.43.0> Application fidelity_rule_engine started on node nonode@nohost
2020-07-13 00:31:54.258 [info] <0.43.0> Application absinthe started on node nonode@nohost
2020-07-13 00:31:54.271 [info] <0.43.0> Application poison started on node nonode@nohost
2020-07-13 00:31:54.290 [info] <0.43.0> Application argon2_elixir started on node nonode@nohost
2020-07-13 00:31:54.304 [info] <0.43.0> Application absinthe_ecto started on node nonode@nohost
2020-07-13 00:31:54.326 [info] <0.43.0> Application absinthe_error_payload started on node nonode@nohost
2020-07-13 00:31:54.347 [info] <0.43.0> Application absinthe_plug started on node nonode@nohost
2020-07-13 00:31:54.837 [info] <0.43.0> Application jose started on node nonode@nohost
2020-07-13 00:31:54.839 [info] <0.43.0> Application guardian started on node nonode@nohost
2020-07-13 00:31:54.845 [info] <0.43.0> Application guardian_db started on node nonode@nohost
2020-07-13 00:31:54.850 [info] <0.43.0> Application basic_auth started on node nonode@nohost
2020-07-13 00:31:54.859 [info] <0.43.0> Application pow started on node nonode@nohost
2020-07-13 00:31:55.247 [info] <0.43.0> Application gqlgateway started on node nonode@nohost
2020-07-13 00:40:37.221 [error] <0.1371.0> CRASH REPORT Process <0.1371.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 00:40:37.229 [error] <0.1371.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1314.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 00:40:50.075 [error] <0.1476.0> CRASH REPORT Process <0.1476.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 00:40:50.075 [error] <0.1476.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1420.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 01:05:40.687 [error] <0.1983.0> CRASH REPORT Process <0.1983.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 01:05:40.688 [error] <0.1983.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1979.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 01:05:41.212 [error] <0.2014.0> CRASH REPORT Process <0.2014.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 01:05:41.212 [error] <0.2014.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1980.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 01:05:49.105 [error] <0.2046.0> CRASH REPORT Process <0.2046.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 01:05:49.105 [error] <0.2046.0> Cowboy stream 5 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1981.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 01:07:22.077 [error] <0.2067.0> CRASH REPORT Process <0.2067.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Admin...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 01:07:22.254 [error] <0.2098.0> CRASH REPORT Process <0.2098.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Admin...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-13 01:07:22.255 [error] <0.2098.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2096.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminuserLive.Index for FidelityAppWeb.Router.Helpers.live_path/2. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Edit, id, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.Admin...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-14 23:15:08.620 [info] <0.43.0> Application lager started on node nonode@nohost
2020-07-14 23:15:08.648 [info] <0.43.0> Application gen_stage started on node nonode@nohost
2020-07-14 23:15:08.657 [info] <0.43.0> Application broadway started on node nonode@nohost
2020-07-14 23:15:08.680 [info] <0.43.0> Application xmerl started on node nonode@nohost
2020-07-14 23:15:08.716 [info] <0.43.0> Application sasl started on node nonode@nohost
2020-07-14 23:15:08.733 [info] <0.43.0> Application tools started on node nonode@nohost
2020-07-14 23:15:08.741 [info] <0.43.0> Application jsx started on node nonode@nohost
2020-07-14 23:15:08.750 [info] <0.43.0> Application recon started on node nonode@nohost
2020-07-14 23:15:08.813 [info] <0.43.0> Application credentials_obfuscation started on node nonode@nohost
2020-07-14 23:15:08.814 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2020-07-14 23:15:08.833 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2020-07-14 23:15:08.842 [info] <0.43.0> Application amqp started on node nonode@nohost
2020-07-14 23:15:08.842 [info] <0.43.0> Application broadway_rabbitmq started on node nonode@nohost
2020-07-14 23:15:09.052 [info] <0.43.0> Application fidelity_rule_engine started on node nonode@nohost
2020-07-14 23:15:09.148 [info] <0.43.0> Application absinthe_ecto started on node nonode@nohost
2020-07-14 23:15:09.164 [info] <0.43.0> Application absinthe_error_payload started on node nonode@nohost
2020-07-14 23:15:09.178 [info] <0.43.0> Application absinthe_plug started on node nonode@nohost
2020-07-14 23:15:09.566 [info] <0.43.0> Application jose started on node nonode@nohost
2020-07-14 23:15:09.566 [info] <0.43.0> Application guardian started on node nonode@nohost
2020-07-14 23:15:09.571 [info] <0.43.0> Application guardian_db started on node nonode@nohost
2020-07-14 23:15:09.575 [info] <0.43.0> Application basic_auth started on node nonode@nohost
2020-07-14 23:15:09.585 [info] <0.43.0> Application pow started on node nonode@nohost
2020-07-14 23:15:09.950 [info] <0.43.0> Application mnesia started on node nonode@nohost
2020-07-14 23:15:09.980 [info] <0.43.0> Application gqlgateway started on node nonode@nohost
2020-07-14 23:39:24.013 [error] <0.2299.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:58 gen_server <0.2299.0> terminated with reason: call to undefined function 'Elixir.Map':put/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 58
2020-07-14 23:39:24.110 [error] <0.2299.0>@Elixir.Map:put CRASH REPORT Process <0.2299.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.Map':put(#{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{password => <<"T">>},constraints => ...,...}, action)
2020-07-14 23:39:24.111 [error] <0.478.0>@Elixir.Map:put Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.2299.0> exit with reason call to undefined function 'Elixir.Map':put(#{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{password => <<"T">>},constraints => ...,...}, action) in context child_terminated
2020-07-14 23:39:25.128 [error] <0.2304.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:58 gen_server <0.2304.0> terminated with reason: call to undefined function 'Elixir.Map':put/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 58
2020-07-14 23:39:25.133 [error] <0.2304.0>@Elixir.Map:put CRASH REPORT Process <0.2304.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.Map':put(#{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{password => <<"T">>},constraints => ...,...}, action)
2020-07-14 23:39:25.134 [error] <0.477.0>@Elixir.Map:put Supervisor {<0.477.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.2304.0> exit with reason call to undefined function 'Elixir.Map':put(#{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{password => <<"T">>},constraints => ...,...}, action) in context child_terminated
2020-07-14 23:39:46.150 [error] <0.2423.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:58 gen_server <0.2423.0> terminated with reason: call to undefined function 'Elixir.Map':put/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 58
2020-07-14 23:39:46.159 [error] <0.2423.0>@Elixir.Map:put CRASH REPORT Process <0.2423.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.Map':put(#{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{password => <<"T">>},constraints => ...,...}, action)
2020-07-14 23:39:46.160 [error] <0.476.0>@Elixir.Map:put Supervisor {<0.476.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.2423.0> exit with reason call to undefined function 'Elixir.Map':put(#{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{password => <<"T">>},constraints => ...,...}, action) in context child_terminated
2020-07-14 23:39:47.175 [error] <0.2428.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:58 gen_server <0.2428.0> terminated with reason: call to undefined function 'Elixir.Map':put/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 58
2020-07-14 23:39:47.182 [error] <0.2428.0>@Elixir.Map:put CRASH REPORT Process <0.2428.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.Map':put(#{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{password => <<"T">>},constraints => ...,...}, action)
2020-07-14 23:39:47.183 [error] <0.472.0>@Elixir.Map:put Supervisor {<0.472.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.2428.0> exit with reason call to undefined function 'Elixir.Map':put(#{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{password => <<"T">>},constraints => ...,...}, action) in context child_terminated
2020-07-14 23:41:35.550 [error] <0.2572.0>@Elixir.FidelityAppWeb.AdminuserLive.Edit:handle_event:69 gen_server <0.2572.0> terminated with reason: call to undefined function 'Elixir.FidelityApp.Accounts':update_user_password/2 from 'Elixir.FidelityAppWeb.AdminuserLive.Edit':handle_event/3 line 69
2020-07-14 23:41:35.554 [error] <0.2572.0>@Elixir.FidelityApp.Accounts:update_user_password CRASH REPORT Process <0.2572.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityApp.Accounts':update_user_password(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"password">> => <<"update_user_password">>,<<"password_confirmation">> => <<"update_user_pass...">>})
2020-07-14 23:41:35.558 [error] <0.475.0>@Elixir.FidelityApp.Accounts:update_user_password Supervisor {<0.475.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.2572.0> exit with reason call to undefined function 'Elixir.FidelityApp.Accounts':update_user_password(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, #{<<"password">> => <<"update_user_password">>,<<"password_confirmation">> => <<"update_user_pass...">>}) in context child_terminated
