2020-07-11 12:10:35.264 [error] <0.8690.0> CRASH REPORT Process <0.8690.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:10:35.265 [error] <0.8690.0> Cowboy stream 7 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8665.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:11:24.274 [error] <0.8705.0> CRASH REPORT Process <0.8705.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,153}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:11:24.275 [error] <0.8705.0> Cowboy stream 9 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8665.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,153}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:11:38.260 [error] <0.8774.0> CRASH REPORT Process <0.8774.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,153}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:11:38.260 [error] <0.8774.0> Cowboy stream 15 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8665.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,153}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:12:30.191 [error] <0.8786.0> CRASH REPORT Process <0.8786.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:12:30.192 [error] <0.8786.0> Cowboy stream 17 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8665.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:12:47.417 [error] <0.8856.0> CRASH REPORT Process <0.8856.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-11 12:12:47.418 [error] <0.8856.0> Cowboy stream 23 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.8665.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => role,message => nil,module => nil,reason => nil},[{nil,role,[],[]},{'Elixir.FidelityAppWeb.UserAuth',signed_in_path,1,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,152}]},{'Elixir.FidelityAppWeb.UserAuth',log_in_user,3,[{file,"lib/fidelity_app_web/controllers/user_auth.ex"},{line,36}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/control..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-12 23:56:19.894 [info] <0.43.0> Application lager started on node nonode@nohost
2020-07-12 23:56:19.922 [info] <0.43.0> Application gen_stage started on node nonode@nohost
2020-07-12 23:56:19.930 [info] <0.43.0> Application broadway started on node nonode@nohost
2020-07-12 23:56:20.030 [info] <0.43.0> Application xmerl started on node nonode@nohost
2020-07-12 23:56:20.070 [info] <0.43.0> Application sasl started on node nonode@nohost
2020-07-12 23:56:20.080 [info] <0.43.0> Application tools started on node nonode@nohost
2020-07-12 23:56:20.087 [info] <0.43.0> Application jsx started on node nonode@nohost
2020-07-12 23:56:20.092 [info] <0.43.0> Application recon started on node nonode@nohost
2020-07-12 23:56:20.143 [info] <0.43.0> Application credentials_obfuscation started on node nonode@nohost
2020-07-12 23:56:20.143 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2020-07-12 23:56:20.168 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2020-07-12 23:56:20.177 [info] <0.43.0> Application amqp started on node nonode@nohost
2020-07-12 23:56:20.177 [info] <0.43.0> Application broadway_rabbitmq started on node nonode@nohost
2020-07-12 23:56:20.304 [info] <0.43.0> Application fidelity_rule_engine started on node nonode@nohost
2020-07-12 23:56:20.340 [info] <0.43.0> Application absinthe started on node nonode@nohost
2020-07-12 23:56:20.357 [info] <0.43.0> Application poison started on node nonode@nohost
2020-07-12 23:56:20.377 [info] <0.43.0> Application argon2_elixir started on node nonode@nohost
2020-07-12 23:56:20.459 [info] <0.43.0> Application absinthe_ecto started on node nonode@nohost
2020-07-12 23:56:20.502 [info] <0.43.0> Application absinthe_error_payload started on node nonode@nohost
2020-07-12 23:56:20.519 [info] <0.43.0> Application absinthe_plug started on node nonode@nohost
2020-07-12 23:56:20.921 [info] <0.43.0> Application jose started on node nonode@nohost
2020-07-12 23:56:20.921 [info] <0.43.0> Application guardian started on node nonode@nohost
2020-07-12 23:56:20.929 [info] <0.43.0> Application guardian_db started on node nonode@nohost
2020-07-12 23:56:20.935 [info] <0.43.0> Application basic_auth started on node nonode@nohost
2020-07-12 23:56:20.947 [info] <0.43.0> Application pow started on node nonode@nohost
2020-07-12 23:56:21.347 [info] <0.43.0> Application mnesia started on node nonode@nohost
2020-07-12 23:56:21.368 [info] <0.43.0> Application gqlgateway started on node nonode@nohost
2020-07-12 23:56:25.341 [error] <0.1101.0> CRASH REPORT Process <0.1101.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :to or :external option in redirect/2">>},[{'Elixir.Phoenix.Controller',url,1,[{file,"lib/phoenix/controller.ex"},{line,415}]},{'Elixir.Phoenix.Controller',redirect,2,[{file,"lib/phoenix/controller.ex"},{line,402}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/controllers/user_session_controller.ex"},{line,1}]},{'Elixir.FidelityAppWeb.UserSessionController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-12 23:56:25.375 [error] <0.1101.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1099.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :to or :external option in redirect/2">>},[{'Elixir.Phoenix.Controller',url,1,[{file,"lib/phoenix/controller.ex"},{line,415}]},{'Elixir.Phoenix.Controller',redirect,2,[{file,"lib/phoenix/controller.ex"},{line,402}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/controllers/user_session_controller.ex"},{line,1}]},{'Elixir.FidelityAppWeb.UserSessionController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-12 23:56:27.395 [error] <0.1159.0> CRASH REPORT Process <0.1159.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :to or :external option in redirect/2">>},[{'Elixir.Phoenix.Controller',url,1,[{file,"lib/phoenix/controller.ex"},{line,415}]},{'Elixir.Phoenix.Controller',redirect,2,[{file,"lib/phoenix/controller.ex"},{line,402}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/controllers/user_session_controller.ex"},{line,1}]},{'Elixir.FidelityAppWeb.UserSessionController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-12 23:56:27.396 [error] <0.1159.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1157.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :to or :external option in redirect/2">>},[{'Elixir.Phoenix.Controller',url,1,[{file,"lib/phoenix/controller.ex"},{line,415}]},{'Elixir.Phoenix.Controller',redirect,2,[{file,"lib/phoenix/controller.ex"},{line,402}]},{'Elixir.FidelityAppWeb.UserSessionController',action,2,[{file,"lib/fidelity_app_web/controllers/user_session_controller.ex"},{line,1}]},{'Elixir.FidelityAppWeb.UserSessionController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
